[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "clumpgen"
version = "0.0.1"
dependencies = ["numpy", "trimesh"]

[tool.setuptools]
packages = ["clumpgen"]
